tab_machines=[
	{
		:name => "bsavinelS",
		:ip => "192.168.56.110",
		:cpu => 2,
		:ram => 2048,
		:box => "debian/bookworm64",
		:script => "./scripts/setup-server.sh"
	},
]

Vagrant.configure("2") do |config|
	tab_machines.each do |machine|
		config.vm.provision "shell", path: "./scripts/setup-aliases.sh"
		config.vm.define machine[:name] do |node|
			node.vm.box = machine[:box]
			node.vm.hostname = machine[:name]
			config.vm.network "forwarded_port", guest: 80, host: 8081, auto_correct: false
			node.vm.network "public_network", bridge: "enp0s3", ip: machine[:ip]
			config.vm.synced_folder "./scripts", "/vagrant/scripts", type: "rsync"
			node.vm.provider "virtualbox" do |v|
				v.name = machine[:name]
				v.memory = machine[:ram]
				v.cpus = machine[:cpu]
			end
			node.vm.provision "shell", path: machine[:script]
		end
	end
  end
