tab_machines=[
	{
		:name => "bsavinelS",
		:ip => "192.168.56.110",
		:cpu => 1,
		:ram => 1024,
		:box => "debian/bookworm64",
		:script => "./scripts/server.sh"
	},
	{
		:name => "bsavinelSW",
		:ip => "192.168.56.111",
		:cpu => 1,
		:ram => 1024,
		:box => "debian/bookworm64",
		:script => "./scripts/agent.sh"
	}
]

Vagrant.configure("2") do |config|
	tab_machines.each do |machine|
		config.vm.define machine[:name] do |node|
			node.vm.box = machine[:box]
			node.vm.hostname = machine[:name]
			node.vm.network "public_network", bridge: "enp0s31f6", ip: machine[:ip]
			node.vm.provider "virtualbox" do |v|
				v.name = machine[:name]
				v.memory = machine[:ram]
				v.cpus = machine[:cpu]
			end
			node.vm.provision "shell", path: machine[:script]
		end
	end
  end
