tab_machines=[
	{
		:name => "bsavinelS",
		:ip => "192.168.56.110",
		:cpu => 1,
		:ram => 512,
		:box => "debian/buster64",
	},
	{
		:name => "bsavinelSW",
		:ip => "192.168.56.111",
		:cpu => 1,
		:ram => 512,
		:box => "debian/buster64",
	}
]

Vagrant.configure("2") do |config|
	tab_machines.each do |machine|
		config.vm.define machine[:name] do |node|
			node.vm.box = machine[:box]
			node.vm.hostname = machine[:name]
			node.vm.network "public_network", ip: machine[:ip]
			node.vm.provider "virtualbox" do |v|
				v.name = machine[:name]
				v.memory = machine[:ram]
				v.cpus = machine[:cpu]
			  end
		  end
	  end
  end