apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p4
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: playground
    repoURL: 'http://127.0.0.1:8081/root/test'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false